### ISSUE TITLE
"Wait for Jenkins to start" is broken with e.g. Google OAuth

### ISSUE THREAD

**Issue by hasufell** [emmetog/ansible-jenkins#56]
## Expected Behavior

The "Wait for Jenkins to start" task succeeds.

## Actual Behavior

It doesn't succeed.

## Steps to Reproduce the Problem

  1. configure jenkins with google oauth
  2. redeploy

## Explanation

The main url returns 403 when google oauth is configured. But I think it is actually timing out... from within the playbook it never succeeds nor returns, even after I changed it to:

```yml
---
- include_tasks: "{{ jenkins_install_via }}/start.yml"

- name: Wait for Jenkins to start
  uri:
    url: "{{ jenkins_url }}"
    validate_certs: "{{ jenkins_https_validate_certs }}"
    status_code: [200, 403, 503]
    timeout: 5
  become: false
  register: jenkins_home_content
  # Jenkins will return 503 (service unavailable) on the home page while
  # starting (the "Please wait while Jenkins is getting ready to work" page)
  until: not (jenkins_home_content.status == 503)
  retries: 5
  delay: 5
```

**Comment by nre-ableton** [comment]
I'm not familiar with this specific Jenkins plugin, but if it's anything like the AD plugin, it should allow one system account as a fallback in case of network glitches/outages. Have you configured such an account?

Also, after Ansible times out, can you visit the Jenkins site in a regular web browser? What do you see? Did it start up normally?

Finally, some logging output with at `-vvv` verbosity would be helpful.

**Comment by hasufell** [comment]
> I'm not familiar with this specific Jenkins plugin, but if it's anything like the AD plugin, it should allow one system account as a fallback in case of network glitches/outages. Have you configured such an account?

No and it isn't desired. I think we have bigger problems if google has an outage.

> Also, after Ansible times out, can you visit the Jenkins site in a regular web browser? What do you see? Did it start up normally?

Yes.

It appears the playbook configuration is just not powerful enough, it silently overwrites my `jenkins_url` and I cannot change it:

```
# Previous versions of this role defined jenkins_url as a default variable, but this URL
# did not include the port, and required the user to hard-code the protocol.
- name: Set jenkins_url fact for backwards-compatibility installations
  set_fact:
    jenkins_url: "{{ jenkins_url }}:{{ jenkins_port }}"
  when: jenkins_url is defined
```

Since `jenkins_port` only refers to the port jenkins runs on, not the port the machine is exposed at... this breaks things.
