### ISSUE TITLE
Plugins are not installed at all

### ISSUE THREAD

**Issue by hasufell** [emmetog/ansible-jenkins#57]
```
    - name: install jenkins
      become: yes
      import_role:
        name: emmetog.jenkins
      vars:
        jenkins_version: "2.190.3"
        jenkins_url: xxxxx
        jenkins_port: 8080
        jenkins_install_via: "apt"
        jenkins_home: "/home/jenkins/data"
        jenkins_admin: "xxxxx"
        jenkins_java_opts: "-Djenkins.install.runSetupWizard=false"
        jenkins_config_owner: "jenkins"
        jenkins_config_group: "jenkins"

        # The locations of the configuration files for jenkins
        jenkins_source_dir_configs: "{{ playbook_dir }}/jenkins-configs"
        jenkins_source_dir_jobs: "{{ jenkins_source_dir_configs }}/jobs"

        # config.xml template source
        jenkins_source_config_xml: "{{ jenkins_source_dir_configs }}/config.xml"

        # Include custom files for jenkins installation
        jenkins_include_custom_files: true
        jenkins_custom_files:
          - src: "credentials.xml"
            dest: "credentials.xml"
          - src: "hudson.plugins.git.GitSCM.xml"
            dest: "hudson.plugins.git.GitSCM.xml"
          - src: "hudson.plugins.jira.JiraProjectProperty.xml"
            dest: "hudson.plugins.jira.JiraProjectProperty.xml"
          - src: "jenkins.CLI.xml"
            dest: "jenkins.CLI.xml"
          - src: "jenkins.model.JenkinsLocationConfiguration.xml"
            dest: "jenkins.model.JenkinsLocationConfiguration.xml"
          - src: "jenkins.plugins.slack.SlackNotifier.xml"
            dest: "jenkins.plugins.slack.SlackNotifier.xml"
          - src: "org.jenkinsci.plugins.workflow.flow.GlobalDefaultFlowDurabilityLevel.xml"
            dest: "org.jenkinsci.plugins.workflow.flow.GlobalDefaultFlowDurabilityLevel.xml"

        # Include secrets directory during installation
        jenkins_include_secrets: false
        jenkins_source_secrets: "{{ jenkins_source_dir_configs }}/secrets/"

        # The names of the jobs (config.xml must exist under jenkins_source_dir_jobs/job_name/)
        jenkins_jobs: ["beta"]

        # These plugins will be installed in the jenkins instance
        jenkins_plugins:
          - ace-editor
          - antisamy-markup-formatter
          - apache-httpcomponents-client-4-api
          - authentication-tokens
          - bitbucket
          - bouncycastle-api
          - branch-api
          - build-name-setter
          - build-pipeline-plugin
          - build-timeout
          - cloudbees-folder
          - command-launcher
          - conditional-buildstep
          - config-file-provider
          - copyartifact
          - credentials
          - credentials-binding
          - dashboard-view
          - display-url-api
          - docker-commons
          - docker-workflow
          - durable-task
          - git
          - git-client
          - git-server
          - github
          - github-api
          - github-branch-source
          - google-login
          - gradle
          - handlebars
          - jackson2-api
          - javadoc
          - jdk-tool
          - jquery
          - jquery-detached
          - jsch
          - junit
          - locale
          - lockable-resources
          - mailer
          - matrix-auth
          - matrix-project
          - maven-plugin
          - mercurial
          - momentjs
          - pam-auth
          - parameterized-trigger
          - pipeline-build-step
          - pipeline-github-lib
          - pipeline-graph-analysis
          - pipeline-input-step
          - pipeline-milestone-step
          - pipeline-model-api
          - pipeline-model-declarative-agent
          - pipeline-model-definition
          - pipeline-model-extensions
          - pipeline-rest-api
          - pipeline-stage-step
          - pipeline-stage-tags-metadata
          - pipeline-stage-view
          - plain-credentials
          - rebuild
          - resource-disposer
          - run-condition
          - scm-api
          - script-security
          - ssh
          - ssh-agent
          - ssh-credentials
          - ssh-slaves
          - structs
          - throttle-concurrents
          - timestamper
          - token-macro
          - workflow-aggregator
          - workflow-api
          - workflow-basic-steps
          - workflow-cps
          - workflow-cps-global-lib
          - workflow-durable-task-step
          - workflow-job
          - workflow-multibranch
          - workflow-scm-step
          - workflow-step-api
          - workflow-support
          - ws-cleanup

        # List of sources of custom jenkins plugins to install
        jenkins_custom_plugins:
          - "{{ playbook_dir }}/jenkins-configs/jira-3.0.6.aa180a6.hpi"
          - "{{ playbook_dir }}/jenkins-configs/bbprb-0.3.0.942c650.hpi"
```

ansible log

```
TASK [emmetog.jenkins : Warn if jenkins_url is defined] ********************************************************************************
ok: [jenkins] => {
    "msg": "Please define jenkins_hostname instead of jenkins_url"
}

TASK [emmetog.jenkins : Sanity check Jenkins authentication mechanism variable] ********************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : Sanity check API token] ****************************************************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : Sanity check API username] *************************************************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : Set jenkins_url fact for backwards-compatibility installations] ************************************************
ok: [jenkins]

TASK [emmetog.jenkins : Set jenkins_url fact for HTTP] *********************************************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : Set jenkins_url fact for HTTPS] ********************************************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : include] *******************************************************************************************************
included: /home/maerwald/git/Terraform-Ansible/roles/emmetog.jenkins/tasks/apt/install.yml for jenkins

TASK [emmetog.jenkins : Create Jenkins group] ******************************************************************************************
ok: [jenkins]

TASK [emmetog.jenkins : Create Jenkins user] *******************************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Install apt PPA dependencies] **********************************************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : Install the Debian keyring] ************************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Add Debian experimental repository for OpenJDK] ****************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Add Debian sid repository for OpenJDK] *************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Create pinning file for apt] ***********************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Install apt packages] ******************************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Set default Java version] **************************************************************************************
ok: [jenkins]

TASK [emmetog.jenkins : Add Jenkins key] ***********************************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Add Jenkins repository] ****************************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Install Jenkins binary package] ********************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : include_tasks] *************************************************************************************************
included: /home/maerwald/git/Terraform-Ansible/roles/emmetog.jenkins/tasks/apt/stop.yml for jenkins

TASK [emmetog.jenkins : Jenkins is stopped] ********************************************************************************************
ok: [jenkins]

TASK [emmetog.jenkins : Wait for Jenkins to stop] **************************************************************************************
ok: [jenkins]

TASK [emmetog.jenkins : Set JENKINS_HOME] **********************************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Set Jenkins port for HTTP] *************************************************************************************
ok: [jenkins]

TASK [emmetog.jenkins : Set Jenkins port for HTTPS] ************************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Set Jenkins Java command line options] *************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Ensure correct ownership of JENKINS_HOME directory] ************************************************************
ok: [jenkins]

TASK [emmetog.jenkins : Ensure main configuration file is up to date] ******************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Configure Jenkins location] ************************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Initialize Jenkins secrets dir fact] ***************************************************************************
ok: [jenkins]

TASK [emmetog.jenkins : Copy secrets] **************************************************************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : Ensure correct ownership of secrets directory] *****************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : Copy JKS keystore credentials] *********************************************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : Copy CA signed certificate] ************************************************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : Copy CA certificate private key] *******************************************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : Initialize HTTPS credentials fact] *****************************************************************************
ok: [jenkins]

TASK [emmetog.jenkins : Set JKS keystore credentials] **********************************************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : Set fact for HTTPS certificate file] ***************************************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : Set CA signed certificate credentials] *************************************************************************
skipping: [jenkins]

TASK [emmetog.jenkins : Set Jenkins command line options] ******************************************************************************
changed: [jenkins]

TASK [emmetog.jenkins : include_tasks] *************************************************************************************************
included: /home/maerwald/git/Terraform-Ansible/roles/emmetog.jenkins/tasks/apt/stop.yml for jenkins

TASK [emmetog.jenkins : Jenkins is stopped] ********************************************************************************************
ok: [jenkins]

TASK [emmetog.jenkins : Wait for Jenkins to stop] **************************************************************************************
ok: [jenkins]

TASK [emmetog.jenkins : Create intermediate dirs for custom files] *********************************************************************
ok: [jenkins] => (item={'src': 'credentials.xml', 'dest': 'credentials.xml'})
ok: [jenkins] => (item={'src': 'hudson.plugins.git.GitSCM.xml', 'dest': 'hudson.plugins.git.GitSCM.xml'})
ok: [jenkins] => (item={'src': 'hudson.plugins.jira.JiraProjectProperty.xml', 'dest': 'hudson.plugins.jira.JiraProjectProperty.xml'})
ok: [jenkins] => (item={'src': 'jenkins.CLI.xml', 'dest': 'jenkins.CLI.xml'})
ok: [jenkins] => (item={'src': 'jenkins.model.JenkinsLocationConfiguration.xml', 'dest': 'jenkins.model.JenkinsLocationConfiguration.xml'})
ok: [jenkins] => (item={'src': 'jenkins.plugins.slack.SlackNotifier.xml', 'dest': 'jenkins.plugins.slack.SlackNotifier.xml'})
ok: [jenkins] => (item={'src': 'org.jenkinsci.plugins.workflow.flow.GlobalDefaultFlowDurabilityLevel.xml', 'dest': 'org.jenkinsci.plugins.workflow.flow.GlobalDefaultFlowDurabilityLevel.xml'})

TASK [emmetog.jenkins : Configure custom files] ****************************************************************************************
changed: [jenkins] => (item={'src': 'credentials.xml', 'dest': 'credentials.xml'})
changed: [jenkins] => (item={'src': 'hudson.plugins.git.GitSCM.xml', 'dest': 'hudson.plugins.git.GitSCM.xml'})
changed: [jenkins] => (item={'src': 'hudson.plugins.jira.JiraProjectProperty.xml', 'dest': 'hudson.plugins.jira.JiraProjectProperty.xml'})
changed: [jenkins] => (item={'src': 'jenkins.CLI.xml', 'dest': 'jenkins.CLI.xml'})
changed: [jenkins] => (item={'src': 'jenkins.model.JenkinsLocationConfiguration.xml', 'dest': 'jenkins.model.JenkinsLocationConfiguration.xml'})
changed: [jenkins] => (item={'src': 'jenkins.plugins.slack.SlackNotifier.xml', 'dest': 'jenkins.plugins.slack.SlackNotifier.xml'})
changed: [jenkins] => (item={'src': 'org.jenkinsci.plugins.workflow.flow.GlobalDefaultFlowDurabilityLevel.xml', 'dest': 'org.jenkinsci.plugins.workflow.flow.GlobalDefaultFlowDurabilityLevel.xml'})

TASK [emmetog.jenkins : Custom plugins are installed] **********************************************************************************
changed: [jenkins] => (item=/home/maerwald/git/Terraform-Ansible/jenkins/playbooks/jenkins-configs/jira-3.0.6.aa180a6.hpi)
changed: [jenkins] => (item=/home/maerwald/git/Terraform-Ansible/jenkins/playbooks/jenkins-configs/bbprb-0.3.0.942c650.hpi)

TASK [emmetog.jenkins : include_tasks] *************************************************************************************************
included: /home/maerwald/git/Terraform-Ansible/roles/emmetog.jenkins/tasks/start.yml for jenkins

TASK [emmetog.jenkins : include_tasks] *************************************************************************************************
included: /home/maerwald/git/Terraform-Ansible/roles/emmetog.jenkins/tasks/apt/start.yml for jenkins

TASK [emmetog.jenkins : Jenkins is started] ********************************************************************************************
ok: [jenkins]

```

Instance fails to start, because configuration for google oauth exists, but the plugin is not installed via provisioning.
