### ISSUE TITLE
Configure custom files looping over folder(recurcive)

### ISSUE THREAD

**Issue by pkozlovskiy** [emmetog/ansible-jenkins#9]
Hi! Nice job, I like this role!
I have a dir  like this
config/
  .ssh/
    id_rsa
  prodSlaveFiles/
    ..
  init.groovy.d/
    ..
  credentials.xml
  hudson.plugins.git.GitSCM.xml
  ...

How to set jenkins_custom_files to copy content of folder to jenkins_home?

**Comment by emmetog** [comment]
Hi @pkozlovskiy, glad you find the role useful.

There is an example in the README, does that help? https://github.com/emmetog/ansible-jenkins#example-playbook

```
- hosts: jenkins

  vars:
    jenkins_version: "1.642.4"
    jenkins_url: http://jenkins.example.com
    jenkins_port: 80
    jenkins_install_via: "docker"
    jenkins_jobs:
        - "my-first-job"
        - "another-awesome-job"
    jenkins_include_secrets: true
    jenkins_include_custom_files: true
    jenkins_custom_files:
      - src: "jenkins.plugins.openstack.compute.UserDataConfig.xml"
        dest: "jenkins.plugins.openstack.compute.UserDataConfig.xml"
    jenkins_custom_plugins:
        - "openstack-cloud-plugin/openstack-cloud.jpi"
      
  roles:
    - emmetog.jenkins
```
